# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20170712_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productextras',
            name='extra_name',
        ),
        migrations.RemoveField(
            model_name='productextras',
            name='product_name',
        ),
        migrations.AddField(
            model_name='productextras',
            name='extra_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productextras',
            name='product_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extras',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
