# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-27 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_utilitydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=3000)),
                ('total', models.FloatField()),
                ('paymentType', models.CharField(max_length=200)),
                ('deliveryType', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
