# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-01 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_order_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
