# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20170712_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sub_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
